# Generated by Django 2.2 on 2021-04-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='coments',
            field=models.ManyToManyField(blank=True, to='Blogs.Comments'),
        ),
    ]
