# Generated by Django 2.2 on 2021-04-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0006_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
