# Generated by Django 2.2 on 2021-04-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0008_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='coments',
            field=models.ManyToManyField(blank=True, null=True, to='Blogs.Comments'),
        ),
    ]
